vim.cmd(":se cursorline")
vim.cmd("set guicursor=n-v-c-i:block")
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("set number relativenumber")
vim.cmd("set nu rnu")
vim.g.mapleader = " "
